language: node_js
sudo: required
branches:
  only: master
node_js:
  - 8
script:
  - node --version
  - yarn --version
  - yarn build
  - yarn test:ci
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules

language: node_js
