export declare namespace Grid {
    export interface HorizontalSize {
        is1?: boolean,
        is2?: boolean,
        is3?: boolean,
        is4?: boolean,
        is5?: boolean,
        is6?: boolean,
        is7?: boolean,
        is8?: boolean,
        is9?: boolean,
        is10?: boolean,
        is11?: boolean,
        is12?: boolean,
    }

    export interface Size {
        isFull?: boolean,
        isNarrow?: boolean,
        isThreeQuarters?: boolean,
        isTwoThirds?: boolean,
        IsHalf?: boolean,
        isOneThird?: boolean,
        isOneQuarter?: boolean,
    }

    export interface Offset {
        isOffsetThreeQuarters?: boolean,
        isOffsetTwoThirds?: boolean,
        IsOffsetHalf?: boolean,
        isOffsetOneThird?: boolean,
        isOffsetOneQuarter?: boolean,
        isOffset1?: boolean,
        isOffset2?: boolean,
        isOffset3?: boolean,
        isOffset4?: boolean,
        isOffset5?: boolean,
        isOffset6?: boolean,
        isOffset7?: boolean,
        isOffset8?: boolean,
        isOffset9?: boolean,
        isOffset10?: boolean,
        isOffset11?: boolean,
        isOffset12?: boolean,
    }

    export interface Mobile {
        isFullMobile?: boolean,
        isNarrowMobile?: boolean,
        isThreeQuartersMobile?: boolean,
        isTwoThirdsMobile?: boolean,
        IsHalfMobile?: boolean,
        isOneThirdMobile?: boolean,
        isOneQuarterMobile?: boolean,
        is1Mobile?: boolean,
        is2Mobile?: boolean,
        is3Mobile?: boolean,
        is4Mobile?: boolean,
        is5Mobile?: boolean,
        is6Mobile?: boolean,
        is7Mobile?: boolean,
        is8Mobile?: boolean,
        is9Mobile?: boolean,
        is10Mobile?: boolean,
        is11Mobile?: boolean,
        is12Mobile?: boolean,
        isOffsetThreeQuartersMobile?: boolean,
        isOffsetTwoThirdsMobile?: boolean,
        IsOffsetHalfMobile?: boolean,
        isOffsetOneThirdMobile?: boolean,
        isOffsetOneQuarterMobile?: boolean,
        isOffset1Mobile?: boolean,
        isOffset2Mobile?: boolean,
        isOffset3Mobile?: boolean,
        isOffset4Mobile?: boolean,
        isOffset5Mobile?: boolean,
        isOffset6Mobile?: boolean,
        isOffset7Mobile?: boolean,
        isOffset8Mobile?: boolean,
        isOffset9Mobile?: boolean,
        isOffset10Mobile?: boolean,
        isOffset11Mobile?: boolean,
        isOffset12Mobile?: boolean,
    }

    export interface Tablet {
        isFullTablet?: boolean,
        isNarrowTablet?: boolean,
        isThreeQuartersTablet?: boolean,
        isTwoThirdsTablet?: boolean,
        IsHalfTablet?: boolean,
        isOneThirdTablet?: boolean,
        isOneQuarterTablet?: boolean,
        is1Tablet?: boolean,
        is2Tablet?: boolean,
        is3Tablet?: boolean,
        is4Tablet?: boolean,
        is5Tablet?: boolean,
        is6Tablet?: boolean,
        is7Tablet?: boolean,
        is8Tablet?: boolean,
        is9Tablet?: boolean,
        is10Tablet?: boolean,
        is11Tablet?: boolean,
        is12Tablet?: boolean,
        isOffsetThreeQuartersTablet?: boolean,
        isOffsetTwoThirdsTablet?: boolean,
        IsOffsetHalfTablet?: boolean,
        isOffsetOneThirdTablet?: boolean,
        isOffsetOneQuarterTablet?: boolean,
        isOffset1Tablet?: boolean,
        isOffset2Tablet?: boolean,
        isOffset3Tablet?: boolean,
        isOffset4Tablet?: boolean,
        isOffset5Tablet?: boolean,
        isOffset6Tablet?: boolean,
        isOffset7Tablet?: boolean,
        isOffset8Tablet?: boolean,
        isOffset9Tablet?: boolean,
        isOffset10Tablet?: boolean,
        isOffset11Tablet?: boolean,
        isOffset12Tablet?: boolean,
    }

    export interface Desktop {
        isFullDesktop?: boolean,
        isNarrowDesktop?: boolean,
        isThreeQuartersDesktop?: boolean,
        isTwoThirdsDesktop?: boolean,
        IsHalfDesktop?: boolean,
        isOneThirdDesktop?: boolean,
        isOneQuarterDesktop?: boolean,
        is1Desktop?: boolean,
        is2Desktop?: boolean,
        is3Desktop?: boolean,
        is4Desktop?: boolean,
        is5Desktop?: boolean,
        is6Desktop?: boolean,
        is7Desktop?: boolean,
        is8Desktop?: boolean,
        is9Desktop?: boolean,
        is10Desktop?: boolean,
        is11Desktop?: boolean,
        is12Desktop?: boolean,
        isOffsetThreeQuartersDesktop?: boolean,
        isOffsetTwoThirdsDesktop?: boolean,
        IsOffsetHalfDesktop?: boolean,
        isOffsetOneThirdDesktop?: boolean,
        isOffsetOneQuarterDesktop?: boolean,
        isOffset1Desktop?: boolean,
        isOffset2Desktop?: boolean,
        isOffset3Desktop?: boolean,
        isOffset4Desktop?: boolean,
        isOffset5Desktop?: boolean,
        isOffset6Desktop?: boolean,
        isOffset7Desktop?: boolean,
        isOffset8Desktop?: boolean,
        isOffset9Desktop?: boolean,
        isOffset10Desktop?: boolean,
        isOffset11Desktop?: boolean,
        isOffset12Desktop?: boolean,
    }
}

export function getHorizontalSizeModifiers(props: Grid.HorizontalSize): object {
    return {
        'is-1': props.is1,
        'is-2': props.is2,
        'is-3': props.is3,
        'is-4': props.is4,
        'is-5': props.is5,
        'is-6': props.is6,
        'is-7': props.is7,
        'is-8': props.is8,
        'is-9': props.is9,
        'is-10': props.is10,
        'is-11': props.is11,
        'is-12': props.is12,
    }
}

export function removeHorizontalSizeProps(props: Grid.HorizontalSize) {
    const {
        is1,
        is2,
        is3,
        is4,
        is5,
        is6,
        is7,
        is8,
        is9,
        is10,
        is11,
        is12,
        ...rest } = props;
    return rest;
}

export function getSizeModifiers(props: Grid.Size): object {
    return {
        'is-full': props.isFull,
        'is-narrow': props.isNarrow,
        'is-three-quarters': props.isThreeQuarters,
        'is-two-thirds': props.isTwoThirds,
        'is-half': props.IsHalf,
        'is-one-third': props.isOneThird,
        'is-one-quarter': props.isOneQuarter,
    }
}

export function removeSizeProps(props: Grid.Size) {
    const {
        isFull,
        isNarrow,
        isThreeQuarters,
        isTwoThirds,
        IsHalf,
        isOneThird,
        isOneQuarter,
        ...rest } = props;
    return rest;
}

export function getOffsetModifiers(props: Grid.Offset): object {
    return {
        'is-offset-three-quarters': props.isOffsetThreeQuarters,
        'is-offset-two-thirds': props.isOffsetTwoThirds,
        'is-offset-half': props.IsOffsetHalf,
        'is-offset-one-third': props.isOffsetOneThird,
        'is-offset-one-quarter': props.isOffsetOneQuarter,
        'is-offset-1': props.isOffset1,
        'is-offset-2': props.isOffset2,
        'is-offset-3': props.isOffset3,
        'is-offset-4': props.isOffset4,
        'is-offset-5': props.isOffset5,
        'is-offset-6': props.isOffset6,
        'is-offset-7': props.isOffset7,
        'is-offset-8': props.isOffset8,
        'is-offset-9': props.isOffset9,
        'is-offset-10': props.isOffset10,
        'is-offset-11': props.isOffset11,
        'is-offset-12': props.isOffset12,
    }
}

export function removeOffsetProps(props: Grid.Offset) {
    const {
        isOffsetThreeQuarters,
        isOffsetTwoThirds,
        IsOffsetHalf,
        isOffsetOneThird,
        isOffsetOneQuarter,
        isOffset1,
        isOffset2,
        isOffset3,
        isOffset4,
        isOffset5,
        isOffset6,
        isOffset7,
        isOffset8,
        isOffset9,
        isOffset10,
        isOffset11,
        isOffset12,
        ...rest } = props;
    return rest;
}

export function getMobileModifiers(props: Grid.Mobile): object {
    return {
        'is-full-mobile': props.isFullMobile,
        'is-narrow-mobile': props.isNarrowMobile,
        'is-three-quarters-mobile': props.isThreeQuartersMobile,
        'is-two-thirds-mobile': props.isTwoThirdsMobile,
        'is-half-mobile': props.IsHalfMobile,
        'is-one-third-mobile': props.isOneThirdMobile,
        'is-one-quarter-mobile': props.isOneQuarterMobile,
        'is-1-mobile': props.is1Mobile,
        'is-2-mobile': props.is2Mobile,
        'is-3-mobile': props.is3Mobile,
        'is-4-mobile': props.is4Mobile,
        'is-5-mobile': props.is5Mobile,
        'is-6-mobile': props.is6Mobile,
        'is-7-mobile': props.is7Mobile,
        'is-8-mobile': props.is8Mobile,
        'is-9-mobile': props.is9Mobile,
        'is-10-mobile': props.is10Mobile,
        'is-11-mobile': props.is11Mobile,
        'is-12-mobile': props.is12Mobile,
        'is-offset-three-quarters-mobile': props.isOffsetThreeQuartersMobile,
        'is-offset-two-thirds-mobile': props.isOffsetTwoThirdsMobile,
        'is-offset-half-mobile': props.IsOffsetHalfMobile,
        'is-offset-one-third-mobile': props.isOffsetOneThirdMobile,
        'is-offset-one-quarter-mobile': props.isOffsetOneQuarterMobile,
        'is-offset-1-mobile': props.isOffset1Mobile,
        'is-offset-2-mobile': props.isOffset2Mobile,
        'is-offset-3-mobile': props.isOffset3Mobile,
        'is-offset-4-mobile': props.isOffset4Mobile,
        'is-offset-5-mobile': props.isOffset5Mobile,
        'is-offset-6-mobile': props.isOffset6Mobile,
        'is-offset-7-mobile': props.isOffset7Mobile,
        'is-offset-8-mobile': props.isOffset8Mobile,
        'is-offset-9-mobile': props.isOffset9Mobile,
        'is-offset-10-mobile': props.isOffset10Mobile,
        'is-offset-11-mobile': props.isOffset11Mobile,
        'is-offset-12-mobile': props.isOffset12Mobile,
    }
}

export function removeMobileProps(props: Grid.Mobile) {
    const {
        isFullMobile,
        isNarrowMobile,
        isThreeQuartersMobile,
        isTwoThirdsMobile,
        IsHalfMobile,
        isOneThirdMobile,
        isOneQuarterMobile,
        is1Mobile,
        is2Mobile,
        is3Mobile,
        is4Mobile,
        is5Mobile,
        is6Mobile,
        is7Mobile,
        is8Mobile,
        is9Mobile,
        is10Mobile,
        is11Mobile,
        is12Mobile,
        isOffsetThreeQuartersMobile,
        isOffsetTwoThirdsMobile,
        IsOffsetHalfMobile,
        isOffsetOneThirdMobile,
        isOffsetOneQuarterMobile,
        isOffset1Mobile,
        isOffset2Mobile,
        isOffset3Mobile,
        isOffset4Mobile,
        isOffset5Mobile,
        isOffset6Mobile,
        isOffset7Mobile,
        isOffset8Mobile,
        isOffset9Mobile,
        isOffset10Mobile,
        isOffset11Mobile,
        isOffset12Mobile,
        ...rest } = props;
    return rest;
}

export function getTabletModifiers(props: Grid.Tablet): object {
    return {
        'is-full-tablet': props.isFullTablet,
        'is-narrow-tablet': props.isNarrowTablet,
        'is-three-quarters-tablet': props.isThreeQuartersTablet,
        'is-two-thirds-tablet': props.isTwoThirdsTablet,
        'is-half-tablet': props.IsHalfTablet,
        'is-one-third-tablet': props.isOneThirdTablet,
        'is-one-quarter-tablet': props.isOneQuarterTablet,
        'is-1-tablet': props.is1Tablet,
        'is-2-tablet': props.is2Tablet,
        'is-3-tablet': props.is3Tablet,
        'is-4-tablet': props.is4Tablet,
        'is-5-tablet': props.is5Tablet,
        'is-6-tablet': props.is6Tablet,
        'is-7-tablet': props.is7Tablet,
        'is-8-tablet': props.is8Tablet,
        'is-9-tablet': props.is9Tablet,
        'is-10-tablet': props.is10Tablet,
        'is-11-tablet': props.is11Tablet,
        'is-12-tablet': props.is12Tablet,
        'is-offset-three-quarters-tablet': props.isOffsetThreeQuartersTablet,
        'is-offset-two-thirds-tablet': props.isOffsetTwoThirdsTablet,
        'is-offset-half-tablet': props.IsOffsetHalfTablet,
        'is-offset-one-third-tablet': props.isOffsetOneThirdTablet,
        'is-offset-one-quarter-tablet': props.isOffsetOneQuarterTablet,
        'is-offset-1-tablet': props.isOffset1Tablet,
        'is-offset-2-tablet': props.isOffset2Tablet,
        'is-offset-3-tablet': props.isOffset3Tablet,
        'is-offset-4-tablet': props.isOffset4Tablet,
        'is-offset-5-tablet': props.isOffset5Tablet,
        'is-offset-6-tablet': props.isOffset6Tablet,
        'is-offset-7-tablet': props.isOffset7Tablet,
        'is-offset-8-tablet': props.isOffset8Tablet,
        'is-offset-9-tablet': props.isOffset9Tablet,
        'is-offset-10-tablet': props.isOffset10Tablet,
        'is-offset-11-tablet': props.isOffset11Tablet,
        'is-offset-12-tablet': props.isOffset12Tablet,
    }
}

export function removeTabletProps(props: Grid.Tablet) {
    const {
        isFullTablet,
        isNarrowTablet,
        isThreeQuartersTablet,
        isTwoThirdsTablet,
        IsHalfTablet,
        isOneThirdTablet,
        isOneQuarterTablet,
        is1Tablet,
        is2Tablet,
        is3Tablet,
        is4Tablet,
        is5Tablet,
        is6Tablet,
        is7Tablet,
        is8Tablet,
        is9Tablet,
        is10Tablet,
        is11Tablet,
        is12Tablet,
        isOffsetThreeQuartersTablet,
        isOffsetTwoThirdsTablet,
        IsOffsetHalfTablet,
        isOffsetOneThirdTablet,
        isOffsetOneQuarterTablet,
        isOffset1Tablet,
        isOffset2Tablet,
        isOffset3Tablet,
        isOffset4Tablet,
        isOffset5Tablet,
        isOffset6Tablet,
        isOffset7Tablet,
        isOffset8Tablet,
        isOffset9Tablet,
        isOffset10Tablet,
        isOffset11Tablet,
        isOffset12Tablet,
        ...rest } = props;
    return rest;
}

export function getDesktopModifiers(props: Grid.Desktop): object {
    return {
        'is-full-desktop': props.isFullDesktop,
        'is-narrow-desktop': props.isNarrowDesktop,
        'is-three-quarters-desktop': props.isThreeQuartersDesktop,
        'is-two-thirds-desktop': props.isTwoThirdsDesktop,
        'is-half-desktop': props.IsHalfDesktop,
        'is-one-third-desktop': props.isOneThirdDesktop,
        'is-one-quarter-desktop': props.isOneQuarterDesktop,
        'is-1-desktop': props.is1Desktop,
        'is-2-desktop': props.is2Desktop,
        'is-3-desktop': props.is3Desktop,
        'is-4-desktop': props.is4Desktop,
        'is-5-desktop': props.is5Desktop,
        'is-6-desktop': props.is6Desktop,
        'is-7-desktop': props.is7Desktop,
        'is-8-desktop': props.is8Desktop,
        'is-9-desktop': props.is9Desktop,
        'is-10-desktop': props.is10Desktop,
        'is-11-desktop': props.is11Desktop,
        'is-12-desktop': props.is12Desktop,
        'is-offset-three-quarters-desktop': props.isOffsetThreeQuartersDesktop,
        'is-offset-two-thirds-desktop': props.isOffsetTwoThirdsDesktop,
        'is-offset-half-desktop': props.IsOffsetHalfDesktop,
        'is-offset-one-third-desktop': props.isOffsetOneThirdDesktop,
        'is-offset-one-quarter-desktop': props.isOffsetOneQuarterDesktop,
        'is-offset-1-desktop': props.isOffset1Desktop,
        'is-offset-2-desktop': props.isOffset2Desktop,
        'is-offset-3-desktop': props.isOffset3Desktop,
        'is-offset-4-desktop': props.isOffset4Desktop,
        'is-offset-5-desktop': props.isOffset5Desktop,
        'is-offset-6-desktop': props.isOffset6Desktop,
        'is-offset-7-desktop': props.isOffset7Desktop,
        'is-offset-8-desktop': props.isOffset8Desktop,
        'is-offset-9-desktop': props.isOffset9Desktop,
        'is-offset-10-desktop': props.isOffset10Desktop,
        'is-offset-11-desktop': props.isOffset11Desktop,
        'is-offset-12-desktop': props.isOffset12Desktop,
    }
}

export function removeDesktopProps(props: Grid.Desktop) {
    const {
        isFullDesktop,
        isNarrowDesktop,
        isThreeQuartersDesktop,
        isTwoThirdsDesktop,
        IsHalfDesktop,
        isOneThirdDesktop,
        isOneQuarterDesktop,
        is1Desktop,
        is2Desktop,
        is3Desktop,
        is4Desktop,
        is5Desktop,
        is6Desktop,
        is7Desktop,
        is8Desktop,
        is9Desktop,
        is10Desktop,
        is11Desktop,
        is12Desktop,
        isOffsetThreeQuartersDesktop,
        isOffsetTwoThirdsDesktop,
        IsOffsetHalfDesktop,
        isOffsetOneThirdDesktop,
        isOffsetOneQuarterDesktop,
        isOffset1Desktop,
        isOffset2Desktop,
        isOffset3Desktop,
        isOffset4Desktop,
        isOffset5Desktop,
        isOffset6Desktop,
        isOffset7Desktop,
        isOffset8Desktop,
        isOffset9Desktop,
        isOffset10Desktop,
        isOffset11Desktop,
        isOffset12Desktop,
        ...rest } = props;
    return rest;
}